### ISSUE TITLE
Please provide sample json and sample mapping file

### ISSUE THREAD

**Issue by CrmDev23** [Azure-Samples/DynamicsConnector#1]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by CrmDev23** [comment]
@maxmushkin: Any input from your side?

**Comment by maxmushkin** [comment]
@CrmDev23, please find sample entity create json and sample mapping files inside samples folder.

**Comment by CrmDev23** [comment]
@maxmushkin great, thanks!
